language: node_js
node_js:
  - "12.18.3"

dist: trusty

sudo: required

branches:
  only:
  - main

notifications:
  email:
    recipients:
      - judiazca2@poligran.edu.co
      - lucastillo@poligran.edu.co
      - eivelezb@poligran.edu.co
      - frcontreras3@poligran.edu.co
      - jaruapen@poligran.edu.co
    on_success: always
    on_failure: always

before_script:
  - npm install -g @angular/cli

script:
- ng lint
- ng test --watch=false
- ng build --prod